### ISSUE TITLE
Freemium features do not load

### ISSUE THREAD

**Issue by Andrelopithecus** [wowawi/.github#1]
Hello! 

Screenshot below of the issue occurring.

![image](https://github.com/user-attachments/assets/24b3e524-d710-486f-9d84-4caf512ad2a9)

I noticed when I try to import / export / save now (which are freemium features) it tries to load an ad but it doesn't ever load.

I tried turning off my VPN, turning on tracking, but nothing seemed to remedy the problem.

Steps to reproduce. 

I am on iOS 18.1

Try to use a freemium feature and was met with an "ad loading" screen but never loaded the ad.

**Comment by dbarton-uk** [comment]
Hi there!

Thanks very much for taking the time to report this issue. I haven't come across this in my testing - for me it always seemed to work once I switched tracking on. Most of the time it actually works ok for me with tracking off too. I haven't tested when on a VPN, so I wonder if this maybe related.

I am pretty sure that the issue is down to a shortage of ad supply rather than a coding bug. Available supply is based on a number of things, e.g. where you are located, time of day, whether or not personalised ads are available etc... Turning off VPN and changing privacy options and tracking settings should help the ad supply but it isn't guaranteed and hasn't helped in your case!

One thing I can suggest is too try restarting the app after switching off the VPN. When the app loads it registers with the ad network and I don't think it re-registers when disconnecting from the VPN unless you restart the app (i.e. killing it completely and then restarting). If this doesn't work (or only sometimes works), there is a freemium mode directly from the version menu so you can ensure freemium is active before creating a build and then being unable to save.

I do plan to take another look at some options for sourcing more ads, but there is also a premium option - which would remove the necessity for any ads all :)

It would be great if you would let me know whether or not turning off the VPN and then restarting the app helps, and also whether or not you have noticed standard pop up ads working with tracking off when your is VPN on? Please feel free to email me directly at wowawi@icloud.com.

Thank you again for raising the issue - your feedback is appreciated. I hope my response helps and that you are enjoying the app!

Cheers

**Comment by dbarton-uk** [comment]
Clarified expected behaviour of freemium option, both in app and on help pages.
